Studentdatabase management system/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Studentdatabase_management_system.Data;
using Microsoft.EntityFrameworkCore;
using Studentdatabase_management_system.Models;
using Studentdatabase_management_system.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Studentdatabase_management_system.Controllers
{
   
    public class DetailsController : Controller
    {

        private StudentDbContext context;


        public DetailsController(StudentDbContext DbContext)
        {
            context = DbContext;
        }
       
        public IActionResult StudentDetails()
       {
            List<Student> Students = context.Students.Include(j => j.Batch).ToList();
            ViewBag.Students = Students;
            return View();

        }
    }
}

Studentdatabase management system/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Studentdatabase_management_system.Models;

namespace Studentdatabase_management_system.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Courses()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult ClassSchedule()
        {
            return View();
        }

        public IActionResult TeacherInfo()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Studentdatabase management system/Views/Home/About.cshtml
<h1>What is Carnatic Music</h1>

<iframe width="560" height="315" src="https://www.youtube.com/embed/ZnObqYfb-0M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Studentdatabase management system/Views/Home/ClassSchedule.cshtml
<h1>Class Schedule</h1>


<h3>Basic Batch</h3>

Classes will be on Monday and Friday at 5 pm

<h3>Intermediate Batch</h3>

Classes will be on Tuesday and Thursday at 5 pm


<h3>Advanced Batch</h3>

Classes will be on Saturday and Sunday at 5 pm

Studentdatabase management system/Views/Home/Courses.cshtml
<h1>Online Carnatic Music Vocal Curriculum</h1>
<li>Level 1:</li>
Sarali varisai,Janta varisai, upper stayi varisai, Daattu varisai
Alankarams with akara sadagams
Geetham
Swarajathi
<li>Level 2:</li>
Adi tala varnam
Ata tala varnam
Pada varnam
Small krithis
<li>Level 3:</li>
Advanced krithis
Shyama sasthry swarajathis
Pancharathna krithis
Navavarna krithis
Navagraha krithis
Pancha linga krithis
</li>Level 4:</li>
Manodharma sangeetham
Theory
Viruthams, Paasurams, Thillana, Padams, Javali, Abhangs, Bhajans, Ashtapathis
</li>Level 5:</li>
Pallavi singing

Studentdatabase management system/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


@{

    ViewData["Title"] = "Home Page";
}

    <div class="text-center">

        @if (SignInManager.IsSignedIn(User))
        {
            @if (User.IsInRole("Admin"))
            {
                <script>
                        window.location.href = "@Url.Action("index","admin")";
                </script>
            }
            else
            {
                <script>
                        window.location.href = "@Url.Action("StudentDetails","Details")";
                </script>



            }
        }

    </div>

Studentdatabase management system/Views/Home/TeacherInfo.cshtml
<p>Hi</p>