Studentdatabase management system/Models/Batch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Studentdatabase_management_system.Models
{
    public class Batch
    {
        public string Name { get; set; }
        public int BatchId { get; set; }
        public string Announcement { get; set; }
        public DateTime ClassSchedule { get; set; }
    }
}

Studentdatabase management system/ViewModels/AddBatchViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Studentdatabase_management_system.ViewModels
{
    public class AddBatchViewModel
    {
        [Required]
        public string Name { get; set; }
        public int BatchId { get; set; }
        [Required]
        public string Announcement { get; set; }
        [Required]
        public DateTime ClassSchedule { get; set; }



        public AddBatchViewModel()
        {

        }


    }
}

Studentdatabase management system/ViewModels/EditViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Studentdatabase_management_system.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Studentdatabase_management_system.ViewModels
{
    public class EditViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        public int BatchId { get; set; }

        public List<SelectListItem> Batch { get; set; }

        public Batch Selectedbatch { get; set; }

    



        public EditViewModel()
            {

            }
        public EditViewModel(Student student,List<Batch> Batches)
        {
            Batch = new List<SelectListItem>();
            foreach (Batch batch in Batches)
            {
                SelectListItem selectListItem = new SelectListItem()
                {
                    Value = batch.BatchId.ToString(),
                    Text = batch.Name,
                    Selected = batch.BatchId == student.BatchId ? true : false

                };

                Batch.Add(selectListItem);

            }

            Id = student.Id;
            Name = student.Name;
            Selectedbatch = student.Batch;

        }
      

        }
}

Studentdatabase management system/Controllers/BatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Studentdatabase_management_system.Data;
using Studentdatabase_management_system.Models;
using Studentdatabase_management_system.ViewModels;

namespace Studentdatabase_management_system.Controllers
{
    [Authorize]
    public class BatchController : Controller
    {
        private StudentDbContext context;

        public BatchController (StudentDbContext DbContext)
        {
            context = DbContext;
        }
        [HttpGet]
        public IActionResult AddBatch()
        {
            AddBatchViewModel addbatchviewmodel = new AddBatchViewModel();
            return View(addbatchviewmodel);
        }
        [HttpPost]
        public IActionResult AddBatch(AddBatchViewModel addbatchviewmodel)
        {
            if (ModelState.IsValid)
            {
                Batch batch = new Batch()
                {
                    Name = addbatchviewmodel.Name,
                    Announcement = addbatchviewmodel.Announcement,
                    ClassSchedule = addbatchviewmodel.ClassSchedule
                };
                context.Batches.Add(batch);
                context.SaveChanges();
                return Redirect("/Admin");
            }
            else
            {
                return View("addBatch", addbatchviewmodel);
            }
        }

        public IActionResult BatchDetails(int Id)
        {
             Batch batch = context.Batches.Find(Id);
            AddBatchDetailViewModel addbatchdetailviewmodel = new AddBatchDetailViewModel(batch);
            return View(addbatchdetailviewmodel);
        }
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            Batch batch = context.Batches.Find(Id);
            EditBatchViewModel editBatchViewModel = new EditBatchViewModel(batch);
            return View(editBatchViewModel);
        }

        [HttpPost]
        public IActionResult Edit(EditBatchViewModel editBatchViewModel)
        {

            if (ModelState.IsValid)
            {
               
                Batch batch = context.Batches.Find(editBatchViewModel.BatchId);
                batch.BatchId = editBatchViewModel.BatchId;
                batch.Name = editBatchViewModel.Name;
                batch.ClassSchedule = editBatchViewModel.ClassSchedule;
                batch.Announcement = editBatchViewModel.Announcement;
                context.Batches.Update(batch);
                context.SaveChanges();
                return Redirect("/Admin");

            }
            else
            {
                return View("Edit", editBatchViewModel);
            }
        }
        public IActionResult Delete(int Id)
        {
            Batch batch = context.Batches.Find(Id);

            context.Batches.Remove(batch);
            context.SaveChanges();
            return Redirect("/Admin");

        }
    }

}

Studentdatabase management system/Views/Batch/AddBatch.cshtml
@model Studentdatabase_management_system.ViewModels.AddBatchViewModel
<h1>Add New Batch</h1>
<form asp-controller="Batch" asp-action="AddBatch" method="post">
    <div class="form-group">
        <label asp-for="Name">Batch Name</label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Announcement">Announcements</label>
        <input asp-for="Announcement" />
        <span asp-validation-for="Announcement"></span>
    </div>
    <div class="form-group">
        <label asp-for="ClassSchedule">ClassSchedule</label>
        <input asp-for="ClassSchedule" />
        <span asp-validation-for="ClassSchedule"></span>
    </div>

    <input type="submit" value="Submit" />
</form>

Studentdatabase management system/Views/Batch/BatchDetails.cshtml
@model Studentdatabase_management_system.ViewModels.AddBatchDetailViewModel

<h1>@Model.BatchName</h1>

<table class="table">
    <tr>
        <th>Batch Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Batch Name</th>
        <td>@Model.BatchName</td>
    </tr>
  
    <tr>
        <th>Class Schedule</th>
        <td>@Model.ClassSchedule</td>
    </tr>
    <tr>
        <th>Announcement</th>
        <td>@Model.Announcements</td>
    </tr>
</table>

Studentdatabase management system/Views/Batch/Edit.cshtml
@model Studentdatabase_management_system.ViewModels.EditBatchViewModel
<h1>Edit  Batch</h1>

<form asp-controller="Batch" asp-action="Edit" method="post">
    <div class="form-group">
        <input type="hidden" name="BatchId" value="@Model.BatchId" />

        <label asp-for="Name">Batch Name</label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">

        <label asp-for="Announcement">Announcement</label>
        <input asp-for="Announcement" />
        <span asp-validation-for="Announcement"></span>
    </div>
    <div class="form-group">

        <label asp-for="ClassSchedule">ClassSchedule</label>
        <input asp-for="ClassSchedule" />
        <span asp-validation-for="ClassSchedule"></span>
    </div>

    <input type="submit" value="Update" />
</form>